### ISSUE TITLE
Create a function for IfListIsEmpty and replace 

### ISSUE THREAD

**Issue by ektagarg** [ektagarg/go-ds#1]
**Remove code redundancy**
Create a function to check if linked list is empty and replace this function with the code which is written in all the other functions!

[singlylinklist.go](https://github.com/ektagarg/go-ds/blob/master/linkedlist/singlylinklist/singlylinklist.go)

**Comment by rdrahul** [comment]
hi @ektagarg ! i would like this to take this up. can you assign me on it.

**Comment by ektagarg** [comment]
Hi, @rdrahul! 
Done. Please check.

**Comment by ektagarg** [comment]
@rdrahul It worked perfectly! Thanks 👍
